exclude: "node_modules|.git"
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*json$|.*txt$|.*csv|.*svg"
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, css, scss, markdown, yaml]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              di/public/dist/.*|
              .*node_modules.*|
              .*boilerplate.*|
              di/templates/includes/.*|
              di/public/js/lib/.*|
              di/fixtures/.*\.json
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ["--quiet"]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              di/public/dist/.*|
              cypress/.*|
              .*node_modules.*|
              .*boilerplate.*|
              di/templates/includes/.*|
              di/public/js/lib/.*
          )$

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
