from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def setup_custom_fields():
	custom_fields = {
		"Customer": [
			dict(
				fieldname="ntn_cnic",
				label="NTN / CNIC",
				fieldtype="Data",
				insert_after="customer_group",
			),
			dict(
				fieldname="di_address",
				label="DI Address",
				fieldtype="Data",
				insert_after="ntn_cnic",
			),
			dict(
				fieldname="province",
				label="Province",
				fieldtype="Link",
				options="Province",
				insert_after="di_address",
			),
			dict(
				fieldname="registration_type",
				label="Registration Type",
				fieldtype="Select",
				options="Registered\nUnregistered",
				insert_after="province",
			),
			dict(
				fieldname="enable_digital_invoicing",
				label="Enable Digital Invoicing",
				fieldtype="Check",
				insert_after="registration_type",
			),
		],
		"Supplier": [
			dict(
				fieldname="di_address",
				label="DI Address",
				fieldtype="Data",
				insert_after="country",
			),
			dict(
				fieldname="province",
				label="Province",
				fieldtype="Link",
				options="Province",
				insert_after="di_address",
			),
			dict(
				fieldname="registration_type",
				label="Registration Type",
				fieldtype="Select",
				options="Registered\nUnregistered",
				insert_after="province",
			),
		],
		"Company": [
			dict(
				fieldname="di_settings_tab",
				label="FBR Settings",
				fieldtype="Tab Break",
				insert_after="old_parent",
			),
			dict(
				fieldname="di_sale_types",
				label="Sale Types",
				fieldtype="Table",
				options="Company Sale Type",
				insert_after="di_settings_tab",
			),
		],
		"Item": [
			dict(
				fieldname="tab_di_settings",
				label="DI Settings",
				fieldtype="Tab Break",
				insert_after="uoms",
			),
			dict(
				fieldname="hs_code",
				label="HS Code",
				fieldtype="Link",
				options="HS Code",
				insert_after="tab_di_settings",
			),
			dict(
				fieldname="hs_uom",
				label="HS UOM",
				fieldtype="Link",
				options="HS Uom",
				insert_after="hs_code",
				read_only=1,
				fetch_from="hs_code.uom",
			),
			dict(
				fieldname="column_break_di_setting",
				fieldtype="Column Break",
				insert_after="hs_uom",
			),
			dict(
				fieldname="sale_type",
				label="Sale Type",
				fieldtype="Link",
				options="Sale Type",
				insert_after="column_break_di_setting",
			),
			dict(
				fieldname="sro_item_serial_no",
				label="SRO Item Serial No",
				fieldtype="Data",
				insert_after="sale_type",
			),
			dict(
				fieldname="sro_schedule_no",
				label="SRO Schedule No",
				fieldtype="Data",
				insert_after="sro_item_serial_no",
			),
		],
		"Sales Invoice": [
			dict(
				fieldname="di_section",
				label="Digital Invoicing",
				fieldtype="Section Break",
				insert_after="remarks",
				depends_on="eval:!doc.is_pos",
			),
			dict(
				fieldname="di_integration_id",
				label="FBR Invoice Number",
				fieldtype="Data",
				insert_after="di_section",
				read_only=1,
			),
			dict(
				fieldname="is_di_posted",
				label="Posted to DI",
				fieldtype="Check",
				insert_after="di_integration_id",
				read_only=1,
			),
			dict(
				fieldname="column_break_di",
				fieldtype="Column Break",
				insert_after="is_di_posted",
			),
			dict(
				fieldname="di_posting_datetime",
				label="DI Posting Datetime",
				fieldtype="Datetime",
				insert_after="column_break_di",
				read_only=1,
			),
			dict(
				fieldname="di_invoice_type",
				label="DI Invoice Type",
				fieldtype="Select",
				options="Sale Invoice\nDebit Note",
				insert_after="di_posting_datetime",
				read_only=1,
			),
			dict(
				fieldname="di_scenario_id",
				label="Sandbox Scenario",
				fieldtype="Link",
				options="Sandbox Scenario",
				insert_after="di_invoice_type",
			),
		],
		"Sales Invoice Item": [
			dict(
				fieldname="di_taxes_section",
				label="Digital Invoicing",
				fieldtype="Section Break",
				insert_after="grant_commission",
			),
			dict(
				fieldname="di_hs_code",
				label="HS Code",
				fieldtype="Link",
				options="HS Code",
				insert_after="di_taxes_section",
				fetch_from="item_code.hs_code",
				read_only=1,
    			allow_on_submit=1,
			),
			dict(
				fieldname="di_hs_uom",
				label="HS UOM",
				fieldtype="Link",
				options="HS Uom",
				insert_after="di_hs_code",
				fetch_from="item_code.hs_uom",
				read_only=1,
    			allow_on_submit=1,
			),
			dict(
				fieldname="di_sale_type",
				label="Sale Type",
				fieldtype="Link",
				options="Sale Type",
				insert_after="di_hs_uom",
				fetch_from="item_code.sale_type",
				allow_on_submit=1,
			),
			dict(
				fieldname="column_break_di_item",
				fieldtype="Column Break",
				insert_after="di_sale_type",
			),
			dict(
				fieldname="di_sro_serial_no",
				label="SRO Serial No",
				fieldtype="Data",
				insert_after="column_break_di_item",
				fetch_from="item_code.sro_item_serial_no",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="di_schedule_no",
				label="SRO Schedule No",
				fieldtype="Data",
				insert_after="di_sro_serial_no",
				fetch_from="item_code.sro_schedule_no",
				read_only=1,
				allow_on_submit=1,
			),
			dict(
				fieldname="di_fed_payable",
				label="FED Payable",
				fieldtype="Currency",
				insert_after="di_schedule_no",
				default="0",
				allow_on_submit=1,
			),
		],
		"Purchase Invoice": [
			dict(
				fieldname="di_section",
				label="Digital Invoicing",
				fieldtype="Section Break",
				insert_after="remarks",
			),
			dict(
				fieldname="di_integration_id",
				label="FBR Invoice Number",
				fieldtype="Data",
				insert_after="di_section",
				read_only=1,
			),
			dict(
				fieldname="is_di_posted",
				label="Posted to DI",
				fieldtype="Check",
				insert_after="di_integration_id",
				read_only=1,
			),
			dict(
				fieldname="column_break_di_pi",
				fieldtype="Column Break",
				insert_after="is_di_posted",
			),
			dict(
				fieldname="di_posting_datetime",
				label="DI Posting Datetime",
				fieldtype="Datetime",
				insert_after="column_break_di_pi",
				read_only=1,
			),
		],
		"Purchase Invoice Item": [
			dict(
				fieldname="di_hs_code",
				label="HS Code",
				fieldtype="Link",
				options="HS Code",
				insert_after="item_name",
				fetch_from="item_code.hs_code",
				read_only=1,
				allow_on_submit=1,
			),
		],
		"Sales Taxes and Charges": [
			dict(
				label="Tax Type",
				fieldname="di_tax_type",
				fieldtype="Select",
				insert_after="account_head",
				options="Sales Tax\nFurther Tax\nAdvance Tax",
				in_list_view=1,
			),
		],
		"POS Profile": [
			dict(
				fieldname="di_pos_section",
				label="FBR POS Fiscal",
				fieldtype="Section Break",
				insert_after="applicable_for_users",
				collapsible=1,
			),
			dict(
				fieldname="enable_fbr_integration",
				label="Enable FBR Integration",
				fieldtype="Check",
				insert_after="di_pos_section",
			),
			dict(
				fieldname="fbr_environment",
				label="FBR Environment",
				fieldtype="Select",
				options="Sandbox\nProduction",
				insert_after="enable_fbr_integration",
				depends_on="eval:doc.enable_fbr_integration",
				default="Sandbox",
			),
			dict(
				fieldname="fbr_pos_id",
				label="FBR POS ID",
				fieldtype="Data",
				insert_after="fbr_environment",
				depends_on="eval:doc.enable_fbr_integration",
			),
			dict(
				fieldname="column_break_fbr",
				fieldtype="Column Break",
				insert_after="fbr_pos_id",
			),
			dict(
				fieldname="fbr_bearer_token",
				label="FBR Bearer Token",
				fieldtype="Password",
				insert_after="column_break_fbr",
				depends_on="eval:doc.enable_fbr_integration",
			),
			dict(
				fieldname="fbr_api_url",
				label="FBR API URL (Override)",
				fieldtype="Data",
				insert_after="fbr_bearer_token",
				depends_on="eval:doc.enable_fbr_integration",
				description="Leave blank to use default URL based on environment",
			),
		],
		"Mode of Payment": [
			dict(
				fieldname="fbr_payment_mode_code",
				label="FBR Payment Mode Code",
				fieldtype="Select",
				options="\n1\n2\n3\n4\n5\n6",
				insert_after="type",
				description="1=Cash, 2=Card, 3=Gift Voucher, 4=Loyalty, 5=Mixed, 6=Cheque",
			),
		],
	}

	create_custom_fields(custom_fields)
